spring:
  liquibase:
    change-log: classpath:db/db.changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpaDemo
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
